(cl:in-package detection_msgs-msg)
(cl:export '(ID-VAL
          ID
          REAL_DISTANCE-VAL
          REAL_DISTANCE
          ESTIMATED_DISTANCE-VAL
          ESTIMATED_DISTANCE
          USE_DEPTH-VAL
          USE_DEPTH
          CENTER_X-VAL
          CENTER_X
          CENTER_Y-VAL
          CENTER_Y
          ERROR_HEADING-VAL
          ERROR_HEADING
          ERROR_ALTITUDE-VAL
          ERROR_ALTITUDE
          ALTITUDE-VAL
          ALTITUDE
          CONTROLLER_ERROR-VAL
          CONTROLLER_ERROR
          CONTROL_OUTPUT-VAL
          CONTROL_OUTPUT
          TARGET_LOST-VAL
          TARGET_LOST
          TARGET_DETECTED-VAL
          TARGET_DETECTED
          DISTANCE_CNST-VAL
          DISTANCE_CNST
          DISTANCE_IMM-VAL
          DISTANCE_IMM
          DISTANCE_SINGER-VAL
          DISTANCE_SINGER
          TARGET_X-VAL
          TARGET_X
          TARGET_Y-VAL
          TARGET_Y
          UAV_X-VAL
          UAV_X
          UAV_Y-VAL
          UAV_Y
          REAL_TARGET_X-VAL
          REAL_TARGET_X
          REAL_TARGET_Y-VAL
          REAL_TARGET_Y
          ESTIMATED_TARGET_X-VAL
          ESTIMATED_TARGET_X
          ESTIMATED_TARGET_Y-VAL
          ESTIMATED_TARGET_Y
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
))